### PR TITLE
Added HiFiAdapterFilt container

### PR DESCRIPTION
**Pull request by Ge94**

### CODE REVIEW

**Review by KateSakharova — APPROVED** [review]
Looks good to me!

**Comment by mberacochea** [comment]
@Ge94 do you think you can make a bioconda recipe for this one? Instead of having a custom container?

**Comment by Ge94** [comment]
@mberacochea I can try, at the moment I am writing the tests for this container as a module in nf. Would the tests stay roughly the same?

**Comment by mberacochea** [comment]
> @mberacochea I can try, at the moment I am writing the tests for this container as a module in nf. Would the tests stay roughly the same?

yeah, swapping the container with the bioconda/biocontainers one should have 0 impact

**Pull request merged**
